{{- if (eq "bucketrepo" .Values.jxRequirements.repository) }}
apiVersion: {{ .Values.ingress.apiVersion | default "networking.k8s.io/v1beta1" }}
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
{{- if eq "NodePort" .Values.jxRequirements.ingress.serviceType }}
    jenkins.io/host: "{{ .Values.jxRequirements.ingress.domain }}"
{{- end }}
{{- if .Values.ingress.annotations }}
{{ toYaml .Values.ingress.annotations | indent 4 }}
{{- end }}
  name: bucketrepo
spec:
  rules:
  - http:
      paths:
      - backend:
          serviceName: bucketrepo
          servicePort: 80
{{- if eq "NodePort" .Values.jxRequirements.ingress.serviceType }}
        path: "/bucketrepo"
{{- else if .Values.ingress.customHosts.bucketrepo }}
        path: "/"
    host: {{ .Values.ingress.customHosts.bucketrepo }}
{{- else if .Values.jxRequirements.ingress.domain }}
        path: "/"
    host: {{ .Values.ingress.prefix.bucketrepo }}{{ .Values.jxRequirements.ingress.namespaceSubDomain }}{{ .Values.jxRequirements.ingress.domain }}
{{- end }}
{{- if .Values.jxRequirements.ingress.tls.enabled }}
  tls:
  - hosts:
  {{- if .Values.ingress.customHosts.bucketrepo }}
    - {{ .Values.ingress.customHosts.bucketrepo }}
  {{- else }}
    - {{ .Values.ingress.prefix.bucketrepo }}{{ .Values.jxRequirements.ingress.namespaceSubDomain }}{{ .Values.jxRequirements.ingress.domain }}
  {{- end }}
{{- if .Values.bucketrepo.ingress.tls.secretName }}
    secretName: "{{ .Values.bucketrepo.ingress.tls.secretName }}"
{{- else if .Values.jxRequirements.ingress.tls.secretName }}
    secretName: "{{ .Values.jxRequirements.ingress.tls.secretName }}"
{{- else if .Values.jxRequirements.ingress.tls.production }}
    secretName: "tls-{{ .Values.jxRequirements.ingress.domain | replace "." "-" }}-p"
{{- else }}
    secretName: "tls-{{ .Values.jxRequirements.ingress.domain | replace "." "-" }}-s"
{{- end }}
{{- end }}
{{- end }}
