apiVersion: v1
kind: ConfigMap
metadata:
  name: jenkins-x-docker-registry
  annotations:
    expose.config.fabric8.io/clusterip-port-if-empty-key: docker.registry
data:
  kaniko.flags: "{{ .Values.kaniko.flags }}"
{{- if eq "gke" .Values.jxRequirements.cluster.provider }}
  docker.registry: {{ .Values.jxRequirements.cluster.registry | default "gcr.io" }}
{{- else }}
  docker.registry: {{ .Values.jxRequirements.cluster.registry | default "docker-registry" }}
{{- end }}
{{- if .Values.jxRequirements.cluster.dockerRegistryOrg }}
  docker.registry.org: {{ .Values.jxRequirements.cluster.dockerRegistryOrg }}
{{- end }}