apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: jenkinsx-aggregate-view
  labels:
    app.kubernetes.io/instance: default
    app.kubernetes.io/part-of: jenkins-x
    rbac.authorization.k8s.io/aggregate-to-view: "true"
rules:
  - apiGroups:
      - jenkins.io
      - comcast.github.io
    resources:
      - "*"
    verbs:
      - get
      - list
      - watch