{{- if eq .Values.jxRequirements.autoUpdate.enabled true }}
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: jx-boot-upgrade
spec:
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: 1
  jobTemplate:
    metadata:
      creationTimestamp: null
    spec:
      template:
        metadata:
          creationTimestamp: null
          labels:
            app: jenkins-x-upgrade-processor
            release: jx
        spec:
          containers:
          - args:
            - upgrade
            - boot
            - --latest-release=true
            command:
            - jx
            image: gcr.io/jenkinsxio/builder-go:{{ .Values.versions.builders }}
            imagePullPolicy: Always
            name: jenkins-x-upgrade-processor
            resources: {}
            terminationMessagePath: /dev/termination-log
            terminationMessagePolicy: File
          dnsPolicy: ClusterFirst
          restartPolicy: Never
          schedulerName: default-scheduler
          securityContext: {}
          terminationGracePeriodSeconds: 30
          serviceAccountName: tekton-bot
  successfulJobsHistoryLimit: 3
  schedule: {{ .Values.jxRequirements.autoUpdate.schedule | default "0 12 */5 * *" | quote }}
  suspend: false
{{- end }}
