chartmuseumServiceLink:
  enabled: false
  # specify the external name here for where the chartmuseum should be
  externalname: ""
kaniko:
  # lets you specify additional kaniko flags such as "--insecure" for insecure registries etc
  flags: "--skip-unused-stages --snapshotMode=redo"
schedulers:
  # to enable/disable the default scheduler
  default: true
lighthouseEngine: tekton
basicAuthSecrets:
  enabled: true
pipeline:
  rbac:
    cluster: true
  serviceAccount:
    name: "tekton-bot"
    annotations: {}
  auth:
    git:
      username: "myuser"
      password: "mypwd"
      url: https://github.com
    docker:
      # if specified use the docker config.json style secret like this:
      # https://github.com/tektoncd/pipeline/blob/master/docs/auth.md#configuring-docker-authentication-for-docker
      configJson: "{}"
      # otherwise use basic auth style secret
      username:
      password:
      url: https://index.docker.io/v1/
      # url: https://gcr.io
      host: docker.io
      email: jenkins-x@googlecloud.com
bucketrepo:
  ingress:
    tls:
      secretName: ""
chartmuseum:
  ingress:
    tls:
      secretName: ""
docker-registry:
  enabled: false
  ingress:
    tls:
      secretName: ""
hook:
  ingress:
    tls:
      secretName: ""
nexus:
  ingress:
    tls:
      secretName: ""
# TODO we want to remove exposecontroller at some point
exposer: Ingress
extensions:
  enabled: true
ingress:
  annotations: {}
  #      kubernetes.io/ingress.class: nginx
  # from v1.22 onwards:
  apiVersion: networking.k8s.io/v1
  #apiVersion: networking.k8s.io/v1beta1

  # ingress path type
  pathType: ImplementationSpecific
  # define the ingress prefixes for the different services
  prefix:
    bucketrepo: bucketrepo
    chartmuseum: chartmuseum
    hook: hook
    nexus: nexus
    dockerRegistry: docker-registry
  # allows you to specify custom hosts
  customHosts:
    bucketrepo: ""
    chartmuseum: ""
    hook: ""
    nexus: ""
    dockerRegistry: ""
  # allows you to specify custom ingress class
  customIngressClass:
    bucketrepo: ""
    chartmuseum: ""
    hook: ""
    nexus: ""
    dockerRegistry: ""
nexusServiceLink:
  enabled: false
  # specify the external name here for where the nexus should point
  externalname: ""
teamRoles:
  viewer:
    enabled: true
  team-admin:
    enabled: true
gc:
  activities:
    schedule: "0/30 */3 * * *"
    # extraArgs: ["--release-age", "12h0m0s"] will run jx gitops gc activities --release-age 12h0m0s
    extraArgs: []
  pods:
    schedule: "0/30 */3 * * *"
    extraArgs: []
  jobs:
    schedule: "0/30 */3 * * *"
    extraArgs: ["--namespace", "jx-git-operator"]
versions:
  # jx is the version of the jx-boot image
  jx: 3.2.405
  # updatebot is the version of the jx-updatebot image
  updatebot: 0.2.0
# standard YAML files for jx boot:
secrets:
  adminUser:
    username: "admin"
    password: ""
  chartMuseum:
    username: ""
    password: ""
  featureFlagAPIKey: ""
  dockerConfig: "{}"
  gpg:
    enabled: false
    pubring: ""
    secjenkins: ""
    secring: ""
    trustdb: ""
  kanikoSecret: ""
  mavenSettings: ""
  npmToken: ""
  pipelineUser:
    username: ""
    email: ""
    token: ""
  tektonBucket: ""
jxRequirements:
  autoUpdate:
    enabled: false
    schedule: ""
    autoMerge: false
  bootConfigURL: https://github.com/jenkins-x/jxr-boot-config.git
  buildPacks:
    buildPackLibrary:
      gitRef: master
      gitURL: https://github.com/jenkins-x/jxr-packs-kubernetes.git
  cluster:
    clustername: ""
    devEnvApprovers:
      - someone
    dockerRegistryOrg: ""
    environmentGitOwner: ""
    environmentGitPublic: false
    gitKind: github
    gitName: github
    gitPublic: false
    gitServer: https://github.com
    kanikoFlags: ""
    namespace: jx
    project: ""
    provider: "kubernetes"
    zone: ""
  deployOptions:
    canary: false
    hpa: false
  environments:
    - key: dev
      repository: environment-mycluster-dev
  gitops: true
  ingress:
    domain: ""
    externalDNS: false
    kind: ""
    namespaceSubDomain: -jx.
    serviceType: ""
    tls:
      email: ""
      enabled: false
      production: false
      secretName: ""
    annotations: {}
  pipelineUser:
    username: ""
    email: ""
  repository: nexus
  secretStorage: local
  storage: []
  # - name: foo
  #   url: http://bar
  versionStream:
    ref: master
    url: https://github.com/jenkins-x/jenkins-x-versions.git
  webhook: lighthouse
jx:
  # these variables are used by 'jx gitops variables' to default environment variables
  # into the .jx/variables.sh file which can be overriden on a pre repository basis
  # or during a pipeline by writing to the '.jx/variables.sh' file
  pipelineVariables: {}
  # lets you define image pull secrets that are added to the tekton-bot ServiceAccount
  imagePullSecrets: []
npm:
  secret:
    enabled: false
istio:
  enabled: false
  apiVersion: networking.istio.io/v1beta1
  createGateway: true
  gateway:
    additionalHosts: []
image:
  repository: ghcr.io/jenkins-x/jxboot-helmfile-resources
  tag: 1.1.163
