{{- if and (not (or (eq "bucketrepo" .Values.jxRequirements.repository) (not .Values.jxRequirements.repository) (eq "none" .Values.jxRequirements.repository))) (not .Values.istio.enabled) (eq "httproute" (include "ingressKind" (dict "Values" .Values "component" "chartmuseum"))) }}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
{{- $annotations := include "httpRouteAnnotations" (dict "Values" .Values "component" "chartmuseum") }}
{{- if $annotations }}
  annotations:
  {{- $annotations | nindent 4 }}
{{- end }}
  name: chartmuseum
spec:
{{- $parentRefs := include "httpRouteParentRefs" (dict "Values" .Values "component" "chartmuseum") }}
{{- if trim $parentRefs }}
  parentRefs:
  {{- $parentRefs | nindent 2 }}
{{- end }}
{{- if or .Values.chartmuseum.httpRoute.customHost .Values.jxRequirements.ingress.domain }}
  hostnames:
  - {{ include "httpRouteHostname" (dict "Values" .Values "component" "chartmuseum") }}
{{- end }}
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /
    backendRefs:
    - name: jenkins-x-chartmuseum
      port: 8080
{{- end }}
