{{- if and (eq "nexus" .Values.jxRequirements.repository) (not .Values.istio.enabled) }}
apiVersion: {{ .Values.ingress.apiVersion | default "networking.k8s.io/v1" }}
kind: Ingress
metadata:
  annotations:
  {{- template "ingressAnnotations" . }}
  name: nexus
spec:
  rules:
  - http:
      paths:
{{- if eq .Values.ingress.apiVersion "networking.k8s.io/v1beta1" }}
      - backend:
          serviceName: nexus
          servicePort: 80
{{- else }}
      - pathType: {{ .Values.ingress.pathType | default "ImplementationSpecific" }}
        backend:
          service:
            name: nexus
            port:
              number: 80
{{- end }}
{{- if eq "NodePort" .Values.jxRequirements.ingress.serviceType }}
        path: "/nexus"
{{- else if .Values.ingress.customHosts.nexus }}
        path: "/"
    host: {{ .Values.ingress.customHosts.nexus }}
{{- else if .Values.jxRequirements.ingress.domain }}
        path: "/"
    host: {{ .Values.ingress.prefix.nexus }}{{ .Values.jxRequirements.ingress.namespaceSubDomain }}{{ .Values.jxRequirements.ingress.domain }}
{{- end }}
{{- if .Values.jxRequirements.ingress.tls.enabled }}
  tls:
  - hosts:
  {{- if .Values.ingress.customHosts.nexus }}
    - {{ .Values.ingress.customHosts.nexus }}
  {{- else }}
    - {{ .Values.ingress.prefix.nexus }}{{ .Values.jxRequirements.ingress.namespaceSubDomain }}{{ .Values.jxRequirements.ingress.domain }}
  {{- end }}
{{- if .Values.nexus.ingress.tls.secretName }}
    secretName: "{{ .Values.nexus.ingress.tls.secretName }}"
{{- else if .Values.jxRequirements.ingress.tls.secretName }}
    secretName: "{{ .Values.jxRequirements.ingress.tls.secretName }}"
{{- else if .Values.jxRequirements.ingress.tls.production }}
    secretName: "tls-{{ .Values.jxRequirements.ingress.domain | replace "." "-" }}-p"
{{- else }}
    secretName: "tls-{{ .Values.jxRequirements.ingress.domain | replace "." "-" }}-s"
{{- end }}
{{- end }}
{{- end }}
