{{- if and (or (eq "lighthouse" .Values.jxRequirements.webhook) (eq "prow" .Values.jxRequirements.webhook)) (not .Values.istio.enabled) (eq "httproute" .Values.hook.ingressType) }}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
{{- $annotations := include "httpRouteAnnotations" (dict "Values" .Values "component" "hook") }}
{{- if $annotations }}
  annotations:
  {{- $annotations | nindent 4 }}
{{- end }}
  name: hook
spec:
{{- $parentRefs := include "httpRouteParentRefs" (dict "Values" .Values "component" "hook") }}
{{- if trim $parentRefs }}
  parentRefs:
  {{- $parentRefs | nindent 2 }}
{{- end }}
{{- if or .Values.hook.httpRoute.customHost .Values.jxRequirements.ingress.domain }}
  hostnames:
  - {{ include "httpRouteHostname" (dict "Values" .Values "component" "hook") }}
{{- end }}
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /hook
    backendRefs:
    - name: hook
      port: 80
{{- end }}
