{{- if eq .Values.lighthouseEngine "tekton" }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.pipeline.serviceAccount.name | default "tekton-bot" | quote }}
  {{- if .Values.pipeline.serviceAccount.annotations }}
  annotations: {{ toYaml .Values.pipeline.serviceAccount.annotations | nindent 4 }}
  {{- end }}
secrets:
- name: tekton-container-registry-auth
- name: tekton-git
{{- if gt (len .Values.jx.imagePullSecrets) 0 }}
imagePullSecrets:
{{- range $name := .Values.jx.imagePullSecrets }}
- name: "{{ $name }}"
{{- end }}
{{- end }}
{{- end }}