{{- if eq .Values.lighthouseEngine "tekton" }}
{{- if eq .Values.secrets.kind "ExternalSecret" }}
apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: tekton-git
  labels:
    app.kubernetes.io/component: controller
    app.kubernetes.io/instance: default
    app.kubernetes.io/part-of: tekton-pipelines
    gitops.jenkins-x.io/pipeline: 'namespaces'
  namespace: jx
  annotations:
    secret.jenkins-x.io/schema-object: {{`'{"name":"tekton-git","properties":[{"name":"username","question":"the pipeline username","help":"the user name used by pipelines running in Jenkins X","generator":"gitOperator.username"},{"name":"password","question":"the pipeline token or password","help":"the token or password used by pipelines running in Jenkins X","generator":"gitOperator.password"}],"mandatory":true}'`}}
spec:
  backendType: gcpSecretsManager
  projectId: {{ .Values.jxRequirements.cluster.project }}
  data:
  - name: password
    key: {{ .Values.jxRequirements.cluster.clusterName }}-jx-pipeline-user
    property: token
    version: latest
  - name: username
    key: {{ .Values.jxRequirements.cluster.clusterName }}-jx-pipeline-user
    property: username
    version: latest
  template:
    metadata:
      annotations:
        tekton.dev/git-0: "https://github.com"
        meta.helm.sh/release-name: 'jxboot-helmfile-resources'
        secret.jenkins-x.io/schema-object: {{`'{"name":"tekton-git","properties":[{"name":"username","question":"the pipeline username","help":"the user name used by pipelines running in Jenkins X","generator":"gitOperator.username"},{"name":"password","question":"the pipeline token or password","help":"the token or password used by pipelines running in Jenkins X","generator":"gitOperator.password"}],"mandatory":true}'`}}
      labels:
        app.kubernetes.io/component: controller
        app.kubernetes.io/instance: default
        app.kubernetes.io/part-of: tekton-pipelines
    type: kubernetes.io/basic-auth
{{- else }}
apiVersion: v1
data:
  password: {{ .Values.pipeline.auth.git.password | b64enc | quote }}
  username: {{ .Values.pipeline.auth.git.username | b64enc | quote }}
kind: Secret
metadata:
  name: tekton-git
  annotations:
    tekton.dev/git-0: {{ .Values.pipeline.auth.git.url | quote }}
  labels:
    app.kubernetes.io/component: controller
    app.kubernetes.io/instance: default
    app.kubernetes.io/part-of: tekton-pipelines
type: kubernetes.io/basic-auth
{{- end -}}
{{- end -}}
